apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "taskforge.fullname" . }}
  labels:
    {{- include "taskforge.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "taskforge.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "taskforge.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: PORT
              value: {{ .Values.env.PORT | quote }}
            - name: REDIS_ADDR
              value: {{ .Values.env.REDIS_ADDR | quote }}
            - name: SQLITE_PATH
              value: {{ .Values.env.SQLITE_PATH | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: taskforge-storage
              mountPath: {{ .Values.persistence.mountPath }}
      volumes:
        - name: taskforge-storage
          emptyDir: {}

