apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskforge-worker
  labels:
    app: taskforge-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskforge-worker
  template:
    metadata:
      labels:
        app: taskforge-worker
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8081"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: worker
        image: taskforge-worker:v4
        imagePullPolicy: IfNotPresent
        env:
        - name: REDIS_ADDR
          value: "redis-master.default.svc.cluster.local:6379"
        ports:
        - containerPort: 8081
          name: metrics
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"

